### PR TITLE
docs: fix single tic

### PR DESCRIPTION
**Pull request by donny-son**
Modified unpaired tic in postgis-express documentation

### CODE REVIEW

**Comment by janpio** [comment]
There might be a README template where this is taken from that also needs to be fixed.

**Comment by donny-son** [comment]
don't think it's in this repo though

**Comment by janpio** [comment]
It actually is: https://github.com/prisma/prisma-examples/blob/latest/.github/readmes/typescript/postgis-express/README.md

**Comment by donny-son** [comment]
thanks! I'll close and resubmit a PR

**Pull request closed without merging**
