### PR TITLE
fix(readme): fix download command

### PR DESCRIPTION
**Pull request by Touratica**
Fixes the command for downloading this example.

### CODE REVIEW

**Comment by ruheni** [comment]
Hi 👋🏽

Thanks for the contribution.🙌🏽
I'll merge this PR as soon as the tests pass.

**Comment by janpio** [comment]
Are these READMEs not generated via templates any more @ruheni?

**Comment by ruheni** [comment]
Thanks for catching that @janpio. I missed that.

@Touratica, update the examples template README which is located [here](https://github.com/prisma/prisma-examples/blob/latest/.github/readmes/typescript/rest-nextjs-api-routes-auth/README.md) and then follow the instructions on our [Contributing guide](https://github.com/prisma/prisma-examples/blob/latest/CONTRIBUTING.md#improving-a-readme) to re-generate the example's README. Let me know if you get stumped. 🙂

**Comment by Touratica** [comment]
> Thanks for catching that @janpio. I missed that.
> 
> @Touratica, update the examples template README which is located [here](https://github.com/prisma/prisma-examples/blob/latest/.github/readmes/typescript/rest-nextjs-api-routes-auth/README.md) and then follow the instructions on our [Contributing guide](https://github.com/prisma/prisma-examples/blob/latest/CONTRIBUTING.md#improving-a-readme) to re-generate the example's README. Let me know if you get stumped. 🙂

I think it's done!

**Comment by Touratica** [comment]
Also, when I ran the tool, it changed another README file (I guess someone didn't regenerate the READMEs after changing the template), but I didn't commit that change because it had nothing to do with what I did change.

**Comment by ruheni** [comment]
Thanks for the update. There was no change because the example's README already had the change you were making.

**Pull request merged**
