### PR TITLE
fix(graphql-auth): add graphql-middleware

### PR DESCRIPTION
**Pull request by steebchen**

### CODE REVIEW

**Comment by steebchen** [comment]
hm, why though

**Comment by steebchen** [comment]
hm why tho

**Comment by jorgenskogas** [comment]
I dont't know what changed.. But i had a look in my previous yarn.lock file
```
graphql-yoga@1.18.3:
  version "1.18.3"
  resolved "https://registry.npmjs.org/graphql-yoga/-/graphql-yoga-1.18.3.tgz#047fa511dbef63cf6d6ea7c06a71202d37444844"
  integrity sha512-tR6JYbwLSBVu0Z8M7BIyt1PHhhexmRwneYM8Ru/g2pixrtsWbelBFAXU7bDPhXrqZ49Zxt2zLJ60x3bLNGo/bQ==
  dependencies:
    "@types/aws-lambda" "8.10.13"
    "@types/cors" "^2.8.4"
    "@types/express" "^4.11.1"
    "@types/graphql" "^14.0.0"
    "@types/graphql-deduplicator" "^2.0.0"
    "@types/zen-observable" "^0.5.3"
    apollo-server-express "^1.3.6"
    apollo-server-lambda "1.3.6"
    apollo-upload-server "^7.0.0"
    body-parser-graphql "1.1.0"
    cors "^2.8.4"
    express "^4.16.3"
    graphql "^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0"
    graphql-deduplicator "^2.0.1"
    graphql-import "^0.7.0"
    graphql-middleware "4.0.1"
    graphql-playground-middleware-express "1.7.11"
    graphql-playground-middleware-lambda "1.7.12"
    graphql-subscriptions "^0.5.8"
    graphql-tools "^4.0.0"
    graphql-upload "^8.0.0"
    subscriptions-transport-ws "^0.9.8"
```

If I add `graphql-middleware@4.0.1 to my project it works again.

**Comment by steebchen** [comment]
Ha, thanks @jorgenskogas 😅 kinda did a stupid thing where I followed the peerDependencies recommendation... 4.0.1 works indeed

**Pull request merged**
