### PR TITLE
fix: add build command to heroku example

### PR DESCRIPTION
**Pull request by 2color**

### CODE REVIEW

**Review by divyenduz — COMMENTED** [review]
Is this required or just better practices? Isn't implicit generate enough?

**Comment by 2color** [comment]
I just went through the Heroku guide and the implicit generate didn't work.

**Comment by janpio** [comment]
Can you please open a bug report for that? It totally should, so this needs to be investigated.

**Comment by 2color** [comment]
Opened an issue: https://github.com/prisma/prisma/issues/4210

**Pull request merged**
