### PR TITLE
feat: update to latest nexus-plugin-prisma

### LINKED ISSUE #2094: Update all examples to use nexus-plugin-prisma instead of nexus-prisma
Currently all failing because of DMMF changes.

Internal: https://prisma-company.slack.com/archives/C8AKVD5HU/p1602178040098600

### PR DESCRIPTION
**Pull request by jasonkuhrt**
closes prisma/prisma-examples#2094

### CODE REVIEW

**Comment by jasonkuhrt** [comment]
There's a lot of duplication/almost-duplication in this repo (JS/TS/"experimental"/...). I'm not sure what the status of everything in here is. I just updated it all... Feels like a lot to maintain though?

**Comment by janpio** [comment]
```
  plugins: [nexusPrisma({ experimentalCRUD: true })],
```

Do all these really use the CRUD features? @jasonkuhrt 

> There's a lot of duplication/almost-duplication in this repo (JS/TS/"experimental"/...). I'm not sure what the status of everything in here is. I just updated it all... Feels like a lot to maintain though?

Yep, that is how Devrel wanted to set up the examples - so updating all of them was the right thing to do here.

**Comment by jasonkuhrt** [comment]
@janpio yeah they all used `t.crud` I believe. I went fast and maybe a few don't.

**Comment by janpio** [comment]
Can you please check again? These are the examples we give to our users how to build GraphQL APIs, so it makes sense to make sure the code really is exemplary.

**Comment by jasonkuhrt** [comment]
@janpio done, `graphql-auth` example did not use `t.crud` while all others do.

**Pull request merged**
