### PR TITLE
feat: update example to Next.js 13

### PR DESCRIPTION
**Pull request by Touratica**
Major update to the typescript/rest-nextjs-api-routes example, now using the app router of Next.js 13, which is no longer in beta.

### CODE REVIEW

**Comment by ruheni** [comment]
Hey 👋

Thanks for looking into this. The tests for the typescript/rest-nextjs-api-routes and javascript/rest-nextjs are failing. Could you look into this and resolve the failing tests?

**Comment by Jolg42** [comment]
Note @ruheni that this PR only touches `typescript/rest-nextjs-api-routes` so `javascript/rest-nextjs` should be unrelated.

After a quick check, I found that it's indeed unrelated as `javascript/rest-nextjs` started failing on the `dev` branch since 
since April 30th https://github.com/prisma/prisma-examples/actions/runs/4843082323/jobs/8630445733#step:5:104
with
```
SyntaxError: Unexpected token '||='
from undici (Prisma Client dependency) 
```

But `typescript/rest-nextjs-api-routes` started failing in this PR so we need to figure out what's the problem here with this PR

In the logs I can see 
```
 npm WARN notsup Unsupported engine for next@13.4.1: wanted: {"node":">=16.8.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
```
I think someone needs to switch the Node.js version to 16.8.0 or newer here to solve this, which is defined in https://github.com/prisma/prisma-examples/blob/latest/.github/workflows/test.yaml but it's a global thing, I'll try this here to see if it solved it.

Note: Node.js 14 support for Prisma is going to be dropped very soon in the next release or after.

**Comment by Jolg42** [comment]
All the tests are now passing except
```
test / test (typescript/graphql-hapi-sdl-first) (pull_request) Failing after 29s
test / test (typescript/graphql-hapi) (pull_request) Failing after 29s 
```

So someone from Prisma will need to have a look

**Comment by jharrell** [comment]
Closing this PR, as we've done a lot of work for NextJS 13 and 14 since this PR was opened. Sorry that we didn't get to this sooner and thank you for the work and effort!

**Pull request closed without merging**
