### PR TITLE
refactor: Migrate apollo

### PR DESCRIPTION
**Pull request by ruheni**
refactor issue #2000 updating examples from graphql-yoga to apollo-server

### CODE REVIEW

**Comment by nikolasburk** [comment]
Nice job Alex! 👏

**Comment by ruheni** [comment]
Thank you. 🙂

**Comment by n2ctech** [comment]
This broke the function getUserId in utils.ts as the context object is different on apollo-server. 
Fixed it locally but not allowed to open PRs here.

**Comment by ruheni** [comment]
Hi @n2ctech 👋🏾
Thank you for pointing that out. I'd love to help you create a PR to fix the issue.
Could you try forking the repository and then create a PR with your update?
I'd really appreciate that 🙂

**Pull request merged**
