### PR TITLE
feat(javascript/rest-koa): add Koa example

### PR DESCRIPTION
**Pull request by baabouj**
Adding a REST API example with **Prisma client** and **[Koa](https://koajs.com/)**.

### CODE REVIEW

**Review by ruheni — CHANGES_REQUESTED** [review]
Hey @baabouj 👋🏽

Thank you for your contribution to the Prisma Examples.

This already looks pretty good. Here are a couple of changes that you should make before we merge this in:
- [x] Generate the README file for the example. Navigate to `.github/tools`, run `npm install` and `npm run build-readmes` to generate one
- [x] Add the example to the table in the repo's README — under JavaScript (Node.js) > Backend only
- [x] Add tests for the example — create a folder in `.github/tests/javascript` for this and copy-paste tests from a similar example, e.g., `rest-express`

**Comment by baabouj** [comment]
Hey @ruheni 👋 
Thank you for your comment and I hope these changes fixed the example 😄

**Comment by ruheni** [comment]
Everything looks good. I'll go ahead and merge it. 🎉

Could you share with me your email or Twitter handle I could use to reach out to you?

**Comment by baabouj** [comment]
Yeah of course Alex, here is my email baabouj.dev@gmail.com.
and thanks again 😄

**Pull request merged**
