### PR TITLE
feat(typescript/rest-sveltekit): add SvelteKit example

### PR DESCRIPTION
**Pull request by baabouj**
Added a fullstack example that shows how to use **TypeScript** with [**SvelteKit**](https://kit.svelte.dev/) and **Prisma Client**

### CODE REVIEW

**Comment by ruheni** [comment]
Hey @baabouj 👋🏽

Thank you for your contribution! Sorry for the late response. 

It seems the test is failing because our suite of tests use Node v14 and the minimum version required for Sveltekit is Node v16. Could you try adding two steps in the test script that uses [nvm](https://github.com/nvm-sh/nvm) to install and use Node v16?

i.e:
```bash
nvm install 16.x
nvm use 16.x
#  ...the rest of the test
```

**Comment by baabouj** [comment]
Hey @ruheni 👋 
Thanks for the review 😄 
I was thinking of making the whole suite of tests use Node.js v16 instead of v14, is it okay if I do so?

**Comment by ruheni** [comment]
Hi @baabouj ,
We're intentionally running on the minimum Node.js version because the Prisma examples are used to test Prisma against the minimum version of Node.js.

Could you attempt using nvm to use Node.js v16 for the SvelteKit example?

**Comment by baabouj** [comment]
Hii @ruheni 😄

Here are a few changes I made to make this work :

---
- **`.github\scripts\test-all.sh`**

I removed the following commands :

```diff
- yarn install
- yarn prisma generate
```
since they already exist in each test script inside the  `.github\tests` directory, so no need to rerun them again

---
- **`.github\tests\typescript\rest-sveltekit\run.sh`**

I added nvm to use Node.js v16

---
- **`.github\tests\typescript\testing-express\run.sh`**

this script didn't have a command to install dependencies (since I removed it from **`.github\scripts\test-all.sh`**), so I added it

---

I hope this makes sense :sweat_smile:
And thank u Alex :blush:

**Comment by ruheni** [comment]
Hey @baabouj 👋🏾

Thanks for taking care of it. The change totally makes sense. I actually started making the change in #4194 to make the tests consistent with the instructions on the READMEs. I’ll review the changes and merge this in soon 🙂

**Comment by ruheni** [comment]
Hey @baabouj 👋🏽

The example seems to be broken and I'm running into an Internal server error: 
image

stdout
```

  ➜  Local:   http://127.0.0.1:5173/
  ➜  Network: use --host to expose
fetch failed
TypeError: fetch failed
    at fetch (/workspaces/prisma-examples/typescript/rest-sveltekit/node_modules/undici/index.js:105:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async load (/workspaces/prisma-examples/typescript/rest-sveltekit/src/routes/+page.server.ts:5:19)
    at async load_server_data (file:///workspaces/prisma-examples/typescript/rest-sveltekit/node_modules/@sveltejs/kit/src/runtime/server/page/load_data.js:32:17)
    at async file:///workspaces/prisma-examples/typescript/rest-sveltekit/node_modules/@sveltejs/kit/src/runtime/server/page/index.js:142:13
3:20:03 PM [vite-plugin-svelte] /workspaces/prisma-examples/typescript/rest-sveltekit/src/lib/components/Post.svelte:5:0 A11y: visible, non-interactive elements with an on:click event must be accompanied by an on:keydown, on:keyup, or on:keypress event.
fetch failed
TypeError: fetch failed
    at fetch (/workspaces/prisma-examples/typescript/rest-sveltekit/node_modules/undici/index.js:105:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async load (/workspaces/prisma-examples/typescript/rest-sveltekit/src/routes/+page.server.ts:5:19)
    at async load_server_data (file:///workspaces/prisma-examples/typescript/rest-sveltekit/node_modules/@sveltejs/kit/src/runtime/server/page/load_data.js:32:17)
    at async Promise.all (index 1)
    at async render_data (file:///workspaces/prisma-examples/typescript/rest-sveltekit/node_modules/@sveltejs/kit/src/runtime/server/data/index.js:85:17)
    at async resolve (file:///workspaces/prisma-examples/typescript/rest-sveltekit/node_modules/@sveltejs/kit/src/runtime/server/index.js:237:17)
    at async respond (file:///workspaces/prisma-examples/typescript/rest-sveltekit/node_modules/@sveltejs/kit/src/runtime/server/index.js:293:20)
    at async file:///workspaces/prisma-examples/typescript/rest-sveltekit/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:413:22
fetch failed
```

Could you look into this?

**Comment by baabouj** [comment]
Hey @ruheni 😄 
It seems like there was a problem with `fetch` but it worked totally fine for me 😕 
I replaced the native fetch web API with the provided fetch function, I'm not sure if this will help but I would like you to give it a try and tell me how it went

**Comment by ruheni** [comment]
This looks pretty good, and the app is functional. 🎉

I'll go ahead and merge the PR. Thank you again for the contribution 🙏🏽

**Comment by baabouj** [comment]
Glad it worked! Thanks @ruheni 😄 
I guess when I have some free time, I'll try to add a sveltekit with javascript and prisma example as well.
So see you in the next PR 😆

**Pull request merged**
