### PR TITLE
Simplify Next.js Link component usage

### PR DESCRIPTION
**Pull request by karlhorky**
`legacyBehavior` prop added in #4232

### CODE REVIEW

**Comment by ruheni** [comment]
Hey @karlhorky 👋🏽

Thanks for the contribution. I just tried out the changes you made and it seems to break the example's styles (see attached screenshot). 

image

**Comment by karlhorky** [comment]
What should this look like? Maybe it's because `styled-jsx` is used here?

**Comment by karlhorky** [comment]
I will switch from `styled-jsx` to inline styles :)

**Comment by karlhorky** [comment]
@ruheni instead of switching to inline styles, I moved the style block to a different `<style>` tag. I guess this should be equivalent now.

**Comment by ruheni** [comment]
The links should look something like this: 
image

The latest changes still doesn't resolve the styling

**Comment by karlhorky** [comment]
@ruheni I haven't cloned the repo onto my machine, maybe you can try debugging why it's not working? I would recommend against using the `legacyBehavior` option - this will probably break in the future.

**Pull request closed without merging**
