### PR TITLE
Remove "restart: always" from docker-compose files

### PR DESCRIPTION
**Pull request by brikou**
"restart: always" would make services start (again) whenever you boot your laptop, I don't think this is the expected behaviour.

### CODE REVIEW

**Comment by schickling** [comment]
@dpetrick what are your thoughts on this?

**Comment by dpetrick** [comment]
We can have the examples use the `on-failure` restart policy, which I _assume_ doesn't start the container on reboot, but finding details about that is as difficult as always in the docker docs.

**Comment by brikou** [comment]
I think that people using docker in production knows about restart option. And if Prisma crashes it is better to not hide it. It is dev afterall.

**Comment by abhiaiyer91** [comment]
+1 for on-failure

**Comment by marktani** [comment]
Why did you close this?

**Comment by brikou** [comment]
@marktani I don't think using `on-failure` is the way to do so I've just opened an issue instead to keep it in mind https://github.com/prisma/prisma-examples/issues/64.

**Pull request closed without merging**
