### PR TITLE
fix: use replica set docker image in mongo example

### PR DESCRIPTION
**Pull request by 2color**

### CODE REVIEW

**Review by janpio — COMMENTED** [review]
Tests indicate this work, but further look shows that the tests are actually skipped:
```
running ./databases/mongodb/package.json
ignoring ./databases/mongodb/package.json
```

Change looks good anyway.

**Comment by 2color** [comment]
That's because of https://github.com/prisma/prisma-examples/blob/mongo-preview-fix/.github/scripts/test-all.sh#L18

I'd need to dive deeper into the test suite to make sure we're running the tests for this.

**Comment by 2color** [comment]
Tests fixed! 
Screen Shot 2021-07-14 at 16 09 32

**Comment by janpio** [comment]
Nice work 💚

**Comment by janpio** [comment]
Follow up from this: https://github.com/prisma/prisma-examples/issues/3022

**Pull request merged**
