### PR TITLE
Go graphql auth example

### PR DESCRIPTION
**Pull request by sachaarbonel**
@abhiaiyer91 could you review my code please ? Thank's 
TODOs : 
- [x] better error handling
- [x] adapt readme

### CODE REVIEW

**Comment by nikolasburk** [comment]
Hey @Sach97, we've done a lot of groundwork for the examples last week and are now on a pretty good path to accept contributions again. I'd love to merge this PR for a `graphql-auth` example for Golang. If you are still keen on contributing, it would be awesome if you could update the PR to fit the new structure and be consistent with the other READMEs.

Here are two things you should keep in mind while updating the example:

- Ensure you're using the proper datamodel + GraphQL schema for the example (more info [here](https://github.com/prisma/prisma-examples/blob/master/CONTRIBUTING.md#graphql-server-with-authentication-and-permissions))
- Ensure your README is consistent with the READMEs for the other `graphql-auth` examples (ore info [here](https://github.com/prisma/prisma-examples/blob/master/CONTRIBUTING.md#improving-a-readme))

**Comment by Sach97** [comment]
Hi @nikolasburk I'll be glad to contribute again to Prisma. I'll update my PR asap according to your guidelines.

**Comment by nikolasburk** [comment]
Hey @sachaarbonel, my sincere apologies for the delay. We're not maintaining Prisma 1 examples any more, but I've still merged your PR. I'm sure there are still lots of people that will find it helpful! Thanks a lot!! 🙏

**Comment by sachaarbonel** [comment]
Hey @sachaarbonel, I'm the one that should feel sorry I completely forgot about this. Thank's for merging this anyway.

**Pull request merged**
