### PR TITLE
chore: update typescript/graphql-nextjs example

### LINKED ISSUE #3041: missed a "seed.ts"  file
examples\graphql-nextjs\prisma  ,missed a "seed.ts"  file

### PR DESCRIPTION
**Pull request by koniuszy**
- upgrading nextjs
- using newest @apollo/client lib instead of: @apollo/react-hooks,  @apollo/react-ssr, apollo-boost, apollo-link-http, apollo-link-schema, react-apollo
- moving connectors from all pages to `_app` as 1 provider.
- upgrading apollo-server-micro to 3 (which introduced newest apollo-gql-playground). due to upgrade had to use `cors` and install `micro`
- introducing the nextjs way to expose handler on `/api/` route
- adding prettier for formatting consistency
- moving generated from `/api/` dir to prevent creating pages (nextjs routing)

### CODE REVIEW

**Comment by ruheni** [comment]
Hmm, I was testing this out, and it seems to be missing the seed script. I'll go ahead and add it too for it to match the instructions on the README.

**Comment by koniuszy** [comment]
> Hmm, I was testing this out, and it seems to be missing the seed script. I'll go ahead and add it too for it to match the instructions on the README.

@ruheni 
I fixed the missing seed.ts file and added adjustments around

**Comment by ruheni** [comment]
Thanks for the update!

Could you update `.github/readmes/_using-the-graphql-api-nextjs.md]` to match the contents in this [commit](https://github.com/prisma/prisma-examples/commit/98ca9213f5e5399052c31d5748965fb965ebb2dd)? After that, change directory to [./github/tools](./github/tools) and run `npm run build-readmes`, commit and push the changes.

I've tested everything and after this update, we can finally merge the PR! 🍾

**Comment by ruheni** [comment]
Thank you so much @koniuszy for the contribution! 💚

**Comment by karlhorky** [comment]
@koniuszy am I understanding correctly that this no longer does any server-side fetching (eg. that was done previously via `getInitialProps`)?

I guess if this is the case, it is a slight regression in that it is fetching the data only once React actually renders...?

If this is the case, for an example that uses Next.js to its full potential, my issue #1875 is still valid and should be reopened.

cc @ruheni

**Comment by ruheni** [comment]
@karlhorky, that makes sense, we should have SSR. I'll re-open the issue. 

@koniuszy you'd like to tackle?

**Pull request merged**
